name: Deploy the web service
on:
  push:
    branches:
      - master
      - add-deployment-github-action
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Bootstrap all services
        run: yarn run bootstrap
      - name: Deploy the web service
        run: yarn run deploy --prefix services/web
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
